var photoData = {
    photo:"096-img_0281.jpg.medium.jpeg",
    width:"800",
    height:"600",
    prev:"img_2235.jpg",
    prevThumb:"040-img_2235.jpg.small.jpeg",
    prevThumbOrientation:"vertical",
    next:null,
    nextThumb:null,
    nextThumbOrientation:null,
    index:"3",
    count:"3",
    title:"Test Album",
    footer:"Copyright &copy; Rennie deGraaf 2009. All rights reserved.",
    caption:[
        "Frost on a bush at the Mount Shark ski area.",
        "Spray Valley Provincial Park, Alberta",
        "28 December 2009, 16:50",
    ],
    properties:{
        "File":"img_0281.jpg", 
        "File size":"3.4 MB",
        "Dimensions":"3648x2736 pixels",
        "Exposure time":"1/60 sec",
        "Aperture value":"f/4.0",
        "Camera model":"Canon PowerShot SX10 IS",
        "Focal length":"14.2 mm",
        "Exposure mode":"Auto exposure",
        "Flash":"Flash fired, compulsory flash mode, red-eye reduction mode.",
        "Shutter speed":"5.91 EV (APEX: 7, 1/59 sec.)",
    }
};
